---
# tasks file for lighthouse-role
- name: Setup Nginx
  block:
  - name: Install epel
    become: true
    ansible.builtin.yum:
      name: epel-release
      state: present
  - name: Install nginx
    become: true
    ansible.builtin.yum:
      name: nginx
      state: present
    notify: Start nginx
  - name: Create config
    become: true
    ansible.builtin.template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: '0644'
    notify: Reload nginx
  - name: Flush handlers
    ansible.builtin.meta: flush_handlers
- name: Install Lighthouse
  block:
  - name: Install Git
    become: true
    ansible.builtin.yum:
      name: git
      state: present
  - name: Get LH repo
    become: true
    ansible.builtin.git:
      repo: "{{ lh_repo }}"
      version: master
      dest: "{{ lh_location }}"
  - name: Set LH config
    become: true
    ansible.builtin.template:
      src: templates/lighthouse.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      mode: '0644'
    notify:
      - Reload nginx
  - name: SELinux give access to html directory for nginx
    become: true
    community.general.sefcontext:
      target: '{{ lh_location }}(/.*)?'
      setype: httpd_sys_content_t
      state: present
    notify:
      - Apply SELinux file context
